- name: Install NGINX
  hosts: WEB
  become: true
  tasks:
    - name:  echo -e "\e[33m-----------Script Run Successfully-----------\e[0m"
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Starting NGINX service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
