- name: Template Demo
  hosts: localhost
  connection: local
  become: yes
  vars:
    fruit_name: apple
  tasks:
    - name: Ansible Template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt
